### ISSUE TITLE
启动报错configuration file could not be opened:  open : no such file or directory

### ISSUE THREAD

**Issue by 794086163** [ImmortalD/hdfs-mount#1]
您好，请问下这个Kerberos验证的挂载方式能使用吗？我配置好之后，直接报错了
![image](https://user-images.githubusercontent.com/37607959/191428357-ff1defa5-6f69-416a-b634-22168a6f5de7.png)

**Comment by ImmortalD** [comment]
> 您好，请问下这个Kerberos验证的挂载方式能使用吗？我配置好之后，直接报错了 ![image](https://user-images.githubusercontent.com/37607959/191428357-ff1defa5-6f69-416a-b634-22168a6f5de7.png)

krb5Conf 配置是不是没有

```yaml
...
hdfs:
  kerberos:
    krb5Conf: "/root/krb5.conf"  # 这个配置配有写吗?
...
```
